"""empty message

Revision ID: 117aa0ad44e0
Revises: 270d8b72882c
Create Date: 2015-05-01 17:48:01.502318

"""

# revision identifiers, used by Alembic.
revision = '117aa0ad44e0'
down_revision = '270d8b72882c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
