"""empty message

Revision ID: 1a3f5002c902
Revises: 3071f9359050
Create Date: 2015-05-12 20:58:07.837851

"""

# revision identifiers, used by Alembic.
revision = '1a3f5002c902'
down_revision = '3071f9359050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('realname', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'realname')
    ### end Alembic commands ###
