"""empty message

Revision ID: 21fead4db587
Revises: 4ddc00c7d2ba
Create Date: 2015-04-29 19:12:38.898656

"""

# revision identifiers, used by Alembic.
revision = '21fead4db587'
down_revision = '4ddc00c7d2ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_problem_title'), 'problem', ['title'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_title'), table_name='problem')
    ### end Alembic commands ###
