"""empty message

Revision ID: 3ee3dd188ee5
Revises: a1ec5268412
Create Date: 2015-05-04 13:40:17.736026

"""

# revision identifiers, used by Alembic.
revision = '3ee3dd188ee5'
down_revision = 'a1ec5268412'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problemsetscore', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.drop_column('problemsetscore', 'username')
    op.add_column('user', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_column('user', 'nickname')
    op.add_column('problemsetscore', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('problemsetscore', 'nickname')
    ### end Alembic commands ###
